### PR TITLE
configure next/prev buttons

### PR DESCRIPTION
**Pull request by davidpett**
allow user to customize next/prev buttons.

### CODE REVIEW

**Comment by Chee7ah** [comment]
@davidpett Could you give an example on how you'd customize the buttons? I tried and failed miserably so far.

**Comment by Suven** [comment]
@Chee7ah Did you try it according to swipers api? http://idangero.us/swiper/api/

In general cli-swiper just passes its parameters as they come.

**Comment by davidpett** [comment]
@Chee7ah It allows you to pass a selector for each of the buttons, like: https://ember-twiddle.com/bc3168660ea8677cbab16237ae1ff2c3?openFiles=templates.application.hbs%2C

**Comment by Chee7ah** [comment]
I see! Thank you!

**Pull request merged**
