### PR TITLE
Fix: followFinger by default is true

### PR DESCRIPTION
**Pull request by inez**

### CODE REVIEW

**Comment by Matt-Jensen** [comment]
Right you are.  Although I don't like the idea of repeating the default values that [swiper already does](https://github.com/nolimits4web/Swiper/blob/master/dist/js/swiper.js#L123) . Perhaps we should only configure this option if the property is truthy?

**Comment by inez** [comment]
By default in swiper that property is true, so there is a need to set it only if it's not true (false). The other approach would be to introduce new property like `notFollowFinger` but that I find silly and confusing.

**Comment by Matt-Jensen** [comment]
Ha sorry, I was thinking about that backwards.  You're right, would you be so kind as to merge in latest master and we'll get this merged.

**Comment by inez** [comment]
I'm not sure if that's what you mean but there you go: https://github.com/Suven/ember-cli-swiper/pull/71

**Comment by Matt-Jensen** [comment]
Should have been more specific, I just meant to merge in the master of this repo, however that's done now.

**Pull request merged**
