### PR TITLE
Remove deprecation warning

### PR DESCRIPTION
**Pull request by abercrave**
Using `set` inside a `didInsertElement` hook throws deprecation warnings in development environments. This instead sets the properties during the next run loop.

### CODE REVIEW

**Comment by abercrave** [comment]
Setting properties on next tick is causing tests to fail. I'll try and figure out what's up.

**Comment by djsegal** [comment]
@abercrave, this looks awesome. thanks man

------------------------

and just for reference,

The final difference* between PR #23 and this one is:

+ This PR (@abercrave)
```
initSwiper: Ember.on('didInsertElement', function() {
  Ember.run.scheduleOnce('afterRender', this, function() {
     this.set('swiper', new Swiper(`#${this.get('elementId')}`, this.get('swiperOptions')));
     this.set('registerAs', this);
   });
})
```

+ PR #23 (@djsegal)
```
initSwiper: function () {
  Ember.run.schedule('afterRender', this, function () {
     this.set('swiper', new Swiper(`#${this.get('elementId')}`, this.get('swiperOptions')));
     this.set('registerAs', this);
   });
}.on('init')
```

**\*the difference being `Ember.on('didInsertElement',` vs `}.on('init')`**

**Comment by danconnell** [comment]
:+1:

**Comment by Suven** [comment]
Thanks for the PR and sorry for the long delay!

**Pull request merged**
