### PR TITLE
adding autoplay options

### PR DESCRIPTION
**Pull request by techsoldaten**
Adding autoplay options per #12

### CODE REVIEW

**Comment by Suven** [comment]
Hey (:

Thanks for your PR!

So autoplay has to be set to specific strings?

**Comment by techsoldaten** [comment]
Yes. And they are all described in the API.

http://idangero.us/swiper/api/

autoplay is a number, the ms between advances.

autoplayStopOnLast is true / false, false stops advancement on the last slide.

autoplayDisableOnInteraction is true / false, true means it stops when a user clicks on a slide.

**Comment by techsoldaten** [comment]
Was considering another fork for responsive breakpoints. Know of any way to pass an array as a parameter?

**Comment by Suven** [comment]
How does your PR really work? Are there missing commits? The only thing that is modified, is swipers grabCursor, isn't it?

Regarding the array: You would need to define that attribute in your controller. You might also need to use Embers toArray.

**Comment by techsoldaten** [comment]
@Suven I appreciate you for pointing out the issue. Yeah, I messed something up. 

options.grabCursor should not be there, the appropriate key should be there. Let me fix this tonight.

**Comment by techsoldaten** [comment]
@Suven I tested the last push and it's working for me. Let me know if you see any other issues.

**Pull request merged**
