### PR TITLE
Updated dependencies

### PR DESCRIPTION
**Pull request by cesarizu**
Applied changes from: https://github.com/ember-cli/ember-addon-output/compare/v2.4.0...v2.7.0

This fixes some errors and warnings with new ember versions like: ember-cli/ember-cli-htmlbars#79

### CODE REVIEW

**Comment by Suven** [comment]
Hey!

Thanks for your efforts. I will review the changes (It seems that the patch contained a little bit too much) as soon as possible.

**Comment by cesarizu** [comment]
Thank you. There are some test failures but all related to jshint (that didn't seem to be installed). I tried adding and removing the package and even trunking to fix the .jshintrc files but nothing worked. If you have any idea about that please let me know.

**Comment by sivakumar-kailasam** [comment]
@cesarizu  @Suven a forced rebuild on travis should probably solve the failure.

**Comment by kepek** [comment]
Ping

**Comment by cesarizu** [comment]
I rebased the branch but it still gives an error. I'll look more into it.

**Comment by Suven** [comment]
I'm very sorry that it took that long :/ 

Because it took that long, I decided to go straight for version 2.10.1. I really appreciate your contributions and hope to see you again in this project.

**Pull request closed without merging**
