### PR TITLE
Fix typos on Demos.

### PR DESCRIPTION
**Pull request by aliceyoung9**

### CODE REVIEW

**Comment by aliceyoung9** [comment]
Actually. On second thought, should the change be written in `tests/dummy/app/templates/index.hbs` ?

**Comment by Suven** [comment]
Yup, that would be the more appropriate place since the js-file gets overwritten based on that.

Thanks for your contribution though!

**Comment by aliceyoung9** [comment]
Alright thanks; I'll amend this PR shortly.

**Comment by aliceyoung9** [comment]
Can't change which branches are in this PR, so I'll be sending a new one instead!

**Pull request closed without merging**
